CREATE DATABASE tutorial;
USE tutorial;

CREATE TABLE DEPARTMENTS
(
	DEPID INT PRIMARY KEY,
	NAME VARCHAR(50)
);

CREATE TABLE EMPLOYEES
(
	EMPLOYEEID	INT			PRIMARY KEY,
	DEPID		INT			FOREIGN KEY REFERENCES DEPARTMENTS (DEPID),
	SURNAME		VARCHAR(40),
	NAME		VARCHAR(30),
	BIRTHDATE	DATETIME,
	HEIGHT		FLOAT,
	BOSSID		INT
);

CREATE TABLE SALARIES
(
	SALARYID	INT			PRIMARY KEY,
	PERSONID	INT			FOREIGN KEY REFERENCES EMPLOYEES (EMPLOYEEID),
	GROSS		MONEY,
	SALARYDATE	DATETIME
);

CREATE TABLE BONUSES
(
	BONUSID		INT			PRIMARY KEY,
	PERSONID	INT			FOREIGN KEY REFERENCES EMPLOYEES (EMPLOYEEID),
	DESCRIPT	VARCHAR(100)
);

CREATE TABLE [percent]
(
	[birth date] DATETIME,
	[5O]	INT,
	[col*] INT
);

DROP TABLE [percent];